"""
Gerador de Configurações - Gera arquivos de configuração para todos os protocolos
"""

import os
import json
from typing import Dict, List, Optional, Any
from datetime import datetime
from rich.console import Console
from rich.panel import Panel

console = Console()


class ConfigGenerator:
    """Classe para geração de arquivos de configuração"""
    
    def __init__(self, config_path: str = '/etc/file-server-manager'):
        self.config_path = config_path
        self.main_config_file = os.path.join(config_path, 'server_config.json')
        self.config = self._load_config()
        
    def _load_config(self) -> Dict:
        """Carrega configuração principal"""
        if os.path.exists(self.main_config_file):
            try:
                with open(self.main_config_file, 'r') as f:
                    return json.load(f)
            except Exception:
                pass
        return self._default_config()
    
    def _default_config(self) -> Dict:
        """Retorna configuração padrão"""
        return {
            'version': '1.0.0',
            'created_at': datetime.now().isoformat(),
            'updated_at': datetime.now().isoformat(),
            'base_path': '/srv/files',
            'protocols': {},
            'security': {
                'ssl_enabled': True,
                'ssl_cert_path': '/etc/file-server-manager/ssl/server.crt',
                'ssl_key_path': '/etc/file-server-manager/ssl/server.key',
                'fail2ban_enabled': True,
                'ip_whitelist': [],
                'ip_blacklist': [],
                'max_login_attempts': 5,
                'ban_time_minutes': 30
            },
            'logging': {
                'level': 'INFO',
                'path': '/var/log/file-server-manager',
                'rotation': 'weekly',
                'audit_enabled': True
            },
            'defaults': {
                'quota_mb': None,
                'session_timeout_minutes': 60,
                'max_connections_per_user': 10
            }
        }
    
    def _save_config(self):
        """Salva configuração principal"""
        try:
            os.makedirs(self.config_path, exist_ok=True)
            self.config['updated_at'] = datetime.now().isoformat()
            with open(self.main_config_file, 'w') as f:
                json.dump(self.config, f, indent=2, default=str)
        except Exception as e:
            console.print(f"[red]✗ Erro ao salvar config: {e}[/red]")
    
    def generate_ftp_config(
        self,
        listen_port: int = 21,
        passive_ports: str = "40000-40100",
        anonymous_enable: bool = False,
        local_enable: bool = True,
        write_enable: bool = True,
        chroot_local: bool = True,
        ssl_enable: bool = True,
        ssl_cert_file: str = None,
        ssl_key_file: str = None,
        max_clients: int = 50,
        max_per_ip: int = 5
    ) -> str:
        """
        Gera configuração para vsftpd (FTP)
        
        Returns:
            Caminho do arquivo de configuração gerado
        """
        config_content = f"""# vsftpd configuration file
# Generated by File Server Manager
# Generated at: {datetime.now().isoformat()}

# === Configurações Básicas ===
listen=YES
listen_ipv6=NO
listen_port={listen_port}
write_enable={str(write_enable).lower()}
local_enable={str(local_enable).lower()}

# === Segurança ===
anonymous_enable={str(anonymous_enable).lower()}
local_umask=022
dirmessage_enable=YES
use_sendfile=YES

# === Chroot Jail (prender usuários ao diretório home) ===
chroot_local_user={str(chroot_local).lower()}
allow_writeable_chroot=YES

# === Lista de usuários não presos ao chroot ===
chroot_list_enable=YES
chroot_list_file=/etc/vsftpd.chroot_list

# === Modo Passivo (para firewall/NAT) ===
pasv_enable=YES
pasv_min_port={passive_ports.split('-')[0]}
pasv_max_port={passive_ports.split('-')[1]}

# === Limites ===
max_clients={max_clients}
max_per_ip={max_per_ip}
connect_timeout=60
data_connection_timeout=120

# === Log ===
xferlog_enable=YES
xferlog_file=/var/log/vsftpd.log
xferlog_std_format=YES
log_ftp_protocol=YES

# === PAM ===
pam_service_name=vsftpd
userlist_enable=YES
userlist_file=/etc/vsftpd.user_list
userlist_deny=NO

# === Mensagens ===
dirmessage_enable=YES
message_file=.message

"""

        # Adicionar configurações SSL se habilitado
        if ssl_enable:
            ssl_cert = ssl_cert_file or self.config['security'].get('ssl_cert_path', '/etc/ssl/certs/vsftpd.pem')
            ssl_key = ssl_key_file or self.config['security'].get('ssl_key_path', '/etc/ssl/private/vsftpd.key')
            
            config_content += f"""
# === Configurações SSL/TLS ===
ssl_enable=YES
allow_anon_ssl=NO
force_local_data_ssl=YES
force_local_logon_ssl=YES
ssl_tlsv1=YES
ssl_sslv2=NO
ssl_sslv3=NO
rsa_cert_file={ssl_cert}
rsa_private_key_file={ssl_key}
require_ssl_reuse=NO
ssl_ciphers=HIGH
"""

        # Salvar configuração
        config_file = '/etc/vsftpd.conf'
        try:
            with open(config_file, 'w') as f:
                f.write(config_content)
            console.print(f"[green]✓ Configuração FTP gerada: {config_file}[/green]")
        except PermissionError:
            console.print(f"[yellow]⚠ Permissão negada para {config_file}. Execute como root.[/yellow]")
            # Salvar em local alternativo para visualização
            alt_file = os.path.join(self.config_path, 'vsftpd.conf')
            with open(alt_file, 'w') as f:
                f.write(config_content)
            console.print(f"[yellow]⚠ Configuração salva em: {alt_file}[/yellow]")
            return alt_file
        
        # Salvar no config do manager
        self.config['protocols']['ftp'] = {
            'enabled': True,
            'port': listen_port,
            'passive_ports': passive_ports,
            'ssl_enabled': ssl_enable,
            'anonymous': anonymous_enable,
            'config_file': config_file
        }
        self._save_config()
        
        return config_file
    
    def generate_sftp_config(
        self,
        port: int = 22,
        permit_root_login: bool = False,
        password_auth: bool = True,
        pubkey_auth: bool = True,
        max_auth_tries: int = 3,
        login_grace_time: int = 60,
        sftp_only_users: List[str] = None
    ) -> str:
        """
        Gera configuração para OpenSSH SFTP
        """
        # Ler configuração existente do sshd
        sshd_config_file = '/etc/ssh/sshd_config'
        backup_file = f'{sshd_config_file}.bak'
        
        try:
            if os.path.exists(sshd_config_file):
                with open(sshd_config_file, 'r') as f:
                    existing_config = f.read()
                # Criar backup
                with open(backup_file, 'w') as f:
                    f.write(existing_config)
                console.print(f"[green]✓ Backup criado: {backup_file}[/green]")
        except Exception as e:
            console.print(f"[yellow]⚠ Não foi possível ler config existente: {e}[/yellow]")
            existing_config = ""
        
        # Configurações base
        config_lines = [
            f"# SFTP Configuration - Generated by File Server Manager",
            f"# Generated at: {datetime.now().isoformat()}",
            "",
            f"Port {port}",
            f"PermitRootLogin {'yes' if permit_root_login else 'no'}",
            f"PasswordAuthentication {'yes' if password_auth else 'no'}",
            f"PubkeyAuthentication {'yes' if pubkey_auth else 'no'}",
            f"MaxAuthTries {max_auth_tries}",
            f"LoginGraceTime {login_grace_time}s",
            "",
            "# Configurações de segurança",
            "Protocol 2",
            "X11Forwarding no",
            "AllowTcpForwarding no",
            "PermitTunnel no",
            "ClientAliveInterval 300",
            "ClientAliveCountMax 2",
            "",
        ]
        
        # Configurar SFTP apenas para usuários específicos
        if sftp_only_users:
            config_lines.append("# Usuários restritos ao SFTP")
            for user in sftp_only_users:
                config_lines.extend([
                    f"Match User {user}",
                    "    ForceCommand internal-sftp",
                    "    ChrootDirectory /srv/files/sftp/%u",
                    "    PermitTunnel no",
                    "    AllowTcpForwarding no",
                    "    X11Forwarding no",
                    ""
                ])
        
        # Adicionar configuração padrão de SFTP
        config_lines.extend([
            "# Subsystem SFTP",
            "Subsystem sftp internal-sftp",
            ""
        ])
        
        new_config = '\n'.join(config_lines)
        
        # Salvar configuração
        try:
            with open(sshd_config_file, 'w') as f:
                f.write(new_config)
            console.print(f"[green]✓ Configuração SFTP gerada: {sshd_config_file}[/green]")
        except PermissionError:
            console.print(f"[yellow]⚠ Permissão negada. Execute como root.[/yellow]")
            alt_file = os.path.join(self.config_path, 'sshd_config')
            with open(alt_file, 'w') as f:
                f.write(new_config)
            console.print(f"[yellow]⚠ Configuração salva em: {alt_file}[/yellow]")
            return alt_file
        
        # Salvar no config do manager
        self.config['protocols']['sftp'] = {
            'enabled': True,
            'port': port,
            'config_file': sshd_config_file,
            'sftp_only_users': sftp_only_users or []
        }
        self._save_config()
        
        return sshd_config_file
    
    def generate_nfs_config(
        self,
        exports: Dict[str, Dict] = None,
        nfs_version: str = "4",
        tcp_only: bool = True
    ) -> str:
        """
        Gera configuração para NFS Server
        """
        exports_file = '/etc/exports'
        
        if exports is None:
            exports = {
                '/srv/files/nfs': {
                    'network': '*',
                    'options': ['rw', 'sync', 'no_subtree_check', 'no_root_squash']
                }
            }
        
        config_lines = [
            f"# NFS Exports - Generated by File Server Manager",
            f"# Generated at: {datetime.now().isoformat()}",
            f"# NFS Version: {nfs_version}",
            ""
        ]
        
        for path, config in exports.items():
            network = config.get('network', '*')
            options = ','.join(config.get('options', ['rw', 'sync', 'no_subtree_check']))
            config_lines.append(f"{path} {network}({options})")
        
        config_content = '\n'.join(config_lines)
        
        # Salvar exports
        try:
            with open(exports_file, 'w') as f:
                f.write(config_content)
            console.print(f"[green]✓ Configuração NFS gerada: {exports_file}[/green]")
        except PermissionError:
            console.print(f"[yellow]⚠ Permissão negada. Execute como root.[/yellow]")
            alt_file = os.path.join(self.config_path, 'exports')
            with open(alt_file, 'w') as f:
                f.write(config_content)
            console.print(f"[yellow]⚠ Configuração salva em: {alt_file}[/yellow]")
            return alt_file
        
        # Configurar /etc/nfs.conf.d/
        nfs_conf = f"""# NFS Server Configuration
[nfsd]
vers{nfs_version}=y
"""
        
        try:
            os.makedirs('/etc/nfs.conf.d', exist_ok=True)
            with open('/etc/nfs.conf.d/local.conf', 'w') as f:
                f.write(nfs_conf)
        except Exception:
            pass
        
        # Salvar no config do manager
        self.config['protocols']['nfs'] = {
            'enabled': True,
            'version': nfs_version,
            'exports': exports,
            'config_file': exports_file
        }
        self._save_config()
        
        return exports_file
    
    def generate_smb_config(
        self,
        workgroup: str = "WORKGROUP",
        server_string: str = "File Server",
        shares: Dict[str, Dict] = None,
        security: str = "user",
        encrypt_passwords: bool = True
    ) -> str:
        """
        Gera configuração para Samba (SMB/CIFS)
        """
        smb_conf = '/etc/samba/smb.conf'
        
        if shares is None:
            shares = {
                'global': {
                    'workgroup': workgroup,
                    'server_string': server_string,
                    'security': security,
                    'map_to_guest': 'Never',
                    'dns_proxy': 'no'
                },
                'homes': {
                    'comment': 'Home Directories',
                    'browseable': 'no',
                    'read_only': 'no',
                    'create_mask': '0700',
                    'directory_mask': '0700',
                    'valid_users': '%S'
                },
                'public': {
                    'comment': 'Public Share',
                    'path': '/srv/files/smb/public',
                    'browseable': 'yes',
                    'read_only': 'no',
                    'guest_ok': 'no',
                    'create_mask': '0644',
                    'directory_mask': '0755'
                }
            }
        
        config_lines = [
            f"# Samba Configuration - Generated by File Server Manager",
            f"# Generated at: {datetime.now().isoformat()}",
            ""
        ]
        
        # Seção global
        global_config = shares.get('global', {})
        config_lines.append("[global]")
        config_lines.append(f"   workgroup = {global_config.get('workgroup', workgroup)}")
        config_lines.append(f"   server_string = {global_config.get('server_string', server_string)}")
        config_lines.append(f"   security = {global_config.get('security', security)}")
        
        if encrypt_passwords:
            config_lines.append("   encrypt passwords = yes")
        
        config_lines.append(f"   map to guest = {global_config.get('map_to_guest', 'Never')}")
        config_lines.append(f"   dns proxy = {global_config.get('dns_proxy', 'no')}")
        config_lines.append(f"   log file = /var/log/samba/%m.log")
        config_lines.append(f"   max log size = 1000")
        config_lines.append("")
        
        # Seções de shares
        for share_name, share_config in shares.items():
            if share_name == 'global':
                continue
            
            config_lines.append(f"[{share_name}]")
            for key, value in share_config.items():
                config_lines.append(f"   {key} = {value}")
            config_lines.append("")
        
        config_content = '\n'.join(config_lines)
        
        # Salvar configuração
        try:
            with open(smb_conf, 'w') as f:
                f.write(config_content)
            console.print(f"[green]✓ Configuração Samba gerada: {smb_conf}[/green]")
        except PermissionError:
            console.print(f"[yellow]⚠ Permissão negada. Execute como root.[/yellow]")
            alt_file = os.path.join(self.config_path, 'smb.conf')
            with open(alt_file, 'w') as f:
                f.write(config_content)
            console.print(f"[yellow]⚠ Configuração salva em: {alt_file}[/yellow]")
            return alt_file
        
        # Salvar no config do manager
        self.config['protocols']['smb'] = {
            'enabled': True,
            'workgroup': workgroup,
            'shares': shares,
            'config_file': smb_conf
        }
        self._save_config()
        
        return smb_conf
    
    def generate_webdav_config(
        self,
        server_type: str = "apache",
        port: int = 80,
        ssl_port: int = 443,
        base_path: str = "/srv/files/webdav",
        server_name: str = "localhost",
        ssl_enabled: bool = True
    ) -> str:
        """
        Gera configuração para WebDAV (Apache)
        """
        if server_type == "apache":
            return self._generate_apache_webdav(
                port=port,
                ssl_port=ssl_port,
                base_path=base_path,
                server_name=server_name,
                ssl_enabled=ssl_enabled
            )
        else:
            return self._generate_nginx_webdav(
                port=port,
                ssl_port=ssl_port,
                base_path=base_path,
                server_name=server_name,
                ssl_enabled=ssl_enabled
            )
    
    def _generate_apache_webdav(
        self,
        port: int = 80,
        ssl_port: int = 443,
        base_path: str = "/srv/files/webdav",
        server_name: str = "localhost",
        ssl_enabled: bool = True
    ) -> str:
        """Gera configuração Apache para WebDAV"""
        
        config_content = f"""# Apache WebDAV Configuration
# Generated by File Server Manager
# Generated at: {datetime.now().isoformat()}

# Carregar módulos DAV
LoadModule dav_module modules/mod_dav.so
LoadModule dav_fs_module modules/mod_dav_fs.so
LoadModule dav_lock_module modules/mod_dav_lock.so
LoadModule auth_digest_module modules/mod_auth_digest.so

# Configurações globais DAV
DAVLockDB /var/lib/dav/lockdb

"""

        # VirtualHost HTTP
        config_content += f"""
# VirtualHost HTTP (opcional - redireciona para HTTPS)
<VirtualHost *:{port}>
    ServerName {server_name}
    
    # Redirecionar para HTTPS
    RewriteEngine On
    RewriteCond %{{HTTPS}} off
    RewriteRule ^(.*)$ https://%{{HTTP_HOST}}%{{REQUEST_URI}} [L,R=301]
</VirtualHost>

"""

        # VirtualHost HTTPS
        if ssl_enabled:
            ssl_cert = self.config['security'].get('ssl_cert_path', '/etc/ssl/certs/webdav.crt')
            ssl_key = self.config['security'].get('ssl_key_path', '/etc/ssl/private/webdav.key')
            
            config_content += f"""
# VirtualHost HTTPS
<VirtualHost *:{ssl_port}>
    ServerName {server_name}
    
    # SSL Configuration
    SSLEngine on
    SSLCertificateFile {ssl_cert}
    SSLCertificateKeyFile {ssl_key}
    
    # Document Root
    DocumentRoot {base_path}
    
    <Directory {base_path}>
        DAV On
        Options Indexes FollowSymLinks
        AllowOverride None
        
        # Autenticação Digest
        AuthType Digest
        AuthName "WebDAV Server"
        AuthDigestDomain /
        AuthDigestProvider file
        AuthUserFile /etc/apache2/.davpasswd
        
        # Requer autenticação
        Require valid-user
        
        # Limites
        LimitRequestBody 0
        LimitXMLRequestBody 0
    </Directory>
    
    # Logging
    ErrorLog /var/log/apache2/webdav_error.log
    CustomLog /var/log/apache2/webdav_access.log combined
</VirtualHost>

"""
        else:
            config_content += f"""
# VirtualHost HTTP (sem SSL)
<VirtualHost *:{port}>
    ServerName {server_name}
    
    DocumentRoot {base_path}
    
    <Directory {base_path}>
        DAV On
        Options Indexes FollowSymLinks
        AllowOverride None
        
        AuthType Digest
        AuthName "WebDAV Server"
        AuthDigestDomain /
        AuthDigestProvider file
        AuthUserFile /etc/apache2/.davpasswd
        
        Require valid-user
    </Directory>
</VirtualHost>

"""

        config_file = '/etc/apache2/sites-available/webdav.conf'
        
        try:
            os.makedirs(os.path.dirname(config_file), exist_ok=True)
            with open(config_file, 'w') as f:
                f.write(config_content)
            console.print(f"[green]✓ Configuração WebDAV gerada: {config_file}[/green]")
        except Exception as e:
            console.print(f"[yellow]⚠ Erro: {e}[/yellow]")
            alt_file = os.path.join(self.config_path, 'webdav.conf')
            with open(alt_file, 'w') as f:
                f.write(config_content)
            return alt_file
        
        # Salvar no config do manager
        self.config['protocols']['webdav'] = {
            'enabled': True,
            'server_type': 'apache',
            'port': port,
            'ssl_port': ssl_port,
            'base_path': base_path,
            'ssl_enabled': ssl_enabled,
            'config_file': config_file
        }
        self._save_config()
        
        return config_file
    
    def _generate_nginx_webdav(
        self,
        port: int = 80,
        ssl_port: int = 443,
        base_path: str = "/srv/files/webdav",
        server_name: str = "localhost",
        ssl_enabled: bool = True
    ) -> str:
        """Gera configuração Nginx para WebDAV (requer módulo dav)"""
        
        config_content = f"""# Nginx WebDAV Configuration
# Generated by File Server Manager
# Generated at: {datetime.now().isoformat()}

server {{
    listen {port};
    server_name {server_name};
    
    root {base_path};
    
    # Habilitar WebDAV
    dav_methods PUT DELETE MKCOL COPY MOVE;
    dav_ext_methods PROPFIND OPTIONS;
    
    # Criar diretórios automaticamente
    create_full_put_path on;
    
    # Autenticação básica
    auth_basic "WebDAV Server";
    auth_basic_user_file /etc/nginx/.davpasswd;
    
    # Logging
    access_log /var/log/nginx/webdav_access.log;
    error_log /var/log/nginx/webdav_error.log;
}}

"""
        if ssl_enabled:
            ssl_cert = self.config['security'].get('ssl_cert_path', '/etc/ssl/certs/webdav.crt')
            ssl_key = self.config['security'].get('ssl_key_path', '/etc/ssl/private/webdav.key')
            
            config_content += f"""
server {{
    listen {ssl_port} ssl;
    server_name {server_name};
    
    ssl_certificate {ssl_cert};
    ssl_certificate_key {ssl_key};
    
    root {base_path};
    
    dav_methods PUT DELETE MKCOL COPY MOVE;
    dav_ext_methods PROPFIND OPTIONS;
    create_full_put_path on;
    
    auth_basic "WebDAV Server";
    auth_basic_user_file /etc/nginx/.davpasswd;
}}

"""

        config_file = '/etc/nginx/sites-available/webdav'
        
        try:
            os.makedirs(os.path.dirname(config_file), exist_ok=True)
            with open(config_file, 'w') as f:
                f.write(config_content)
            console.print(f"[green]✓ Configuração WebDAV (Nginx) gerada: {config_file}[/green]")
        except Exception as e:
            console.print(f"[yellow]⚠ Erro: {e}[/yellow]")
            alt_file = os.path.join(self.config_path, 'nginx_webdav.conf')
            with open(alt_file, 'w') as f:
                f.write(config_content)
            return alt_file
        
        self.config['protocols']['webdav'] = {
            'enabled': True,
            'server_type': 'nginx',
            'port': port,
            'ssl_port': ssl_port,
            'base_path': base_path,
            'ssl_enabled': ssl_enabled,
            'config_file': config_file
        }
        self._save_config()
        
        return config_file
    
    def generate_minio_config(
        self,
        port: int = 9000,
        console_port: int = 9001,
        data_dir: str = "/srv/files/s3/data",
        certs_dir: str = "/srv/files/s3/certs"
    ) -> str:
        """
        Gera configuração para MinIO (S3 compatible)
        """
        # Docker Compose para MinIO
        compose_content = f"""# MinIO Docker Compose - Generated by File Server Manager
# Generated at: {datetime.now().isoformat()}

version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "{port}:9000"
      - "{console_port}:9001"
    volumes:
      - {data_dir}:/data
      - {certs_dir}:/root/.minio/certs
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      MINIO_CERTS_DIR: /root/.minio/certs
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

"""

        compose_file = os.path.join(self.config_path, 'minio-docker-compose.yml')
        
        try:
            os.makedirs(data_dir, exist_ok=True)
            os.makedirs(certs_dir, exist_ok=True)
            
            with open(compose_file, 'w') as f:
                f.write(compose_content)
            
            console.print(f"[green]✓ Configuração MinIO gerada: {compose_file}[/green]")
        except Exception as e:
            console.print(f"[red]✗ Erro: {e}[/red]")
            return ""
        
        # Environment file
        env_content = """# MinIO Environment Variables
# Change these values for production!
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin123
"""
        
        env_file = os.path.join(self.config_path, '.minio.env')
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        # Salvar no config do manager
        self.config['protocols']['s3'] = {
            'enabled': True,
            'type': 'minio',
            'port': port,
            'console_port': console_port,
            'data_dir': data_dir,
            'compose_file': compose_file
        }
        self._save_config()
        
        return compose_file
    
    def update_protocol_status(self, protocol: str, enabled: bool):
        """Atualiza status de um protocolo"""
        if protocol in self.config['protocols']:
            self.config['protocols'][protocol]['enabled'] = enabled
            self._save_config()
    
    def get_protocol_config(self, protocol: str) -> Optional[Dict]:
        """Obtém configuração de um protocolo"""
        return self.config['protocols'].get(protocol)
    
    def get_all_configs(self) -> Dict:
        """Retorna todas as configurações"""
        return self.config
    
    def backup_configs(self, backup_path: str = None) -> str:
        """Cria backup das configurações"""
        if backup_path is None:
            backup_path = os.path.join(
                self.config_path,
                f"backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            )
        
        try:
            with open(backup_path, 'w') as f:
                json.dump(self.config, f, indent=2)
            console.print(f"[green]✓ Backup criado: {backup_path}[/green]")
            return backup_path
        except Exception as e:
            console.print(f"[red]✗ Erro no backup: {e}[/red]")
            return ""